library('party')
#d1=read.csv('train6A.csv')
#m1=cforest(y ~ .,data=d1,control=cforest_control(ntree=200))
#i1=varimp(m1)
#d2=read.csv('train6B.csv')
#m2=cforest(y ~ .,data=d2,control=cforest_control(ntree=200))
#i2=varimp(m2)
#d3=read.csv('train6C.csv')
#m3=cforest(y ~ .,data=d3,control=cforest_control(ntree=200))
#i3=varimp(m3)
#d4=read.csv('train6D.csv')
#m4=cforest(y ~ .,data=d4,control=cforest_control(ntree=200))
#i4=varimp(m4)
d5=read.csv('rfimpE.csv')
m5=cforest(y ~ .,data=d5,control=cforest_control(ntree=200))
i5=varimp(m5)
#d6=read.csv('train6F.csv')
#m6=cforest(y ~ .,data=d6,control=cforest_control(ntree=200))
#i6=varimp(m6)
#d7=read.csv('train6G.csv')
#m7=cforest(y ~ .,data=d7,control=cforest_control(ntree=200))
#i7=varimp(m7)
#write.csv(i1+i2+i3+i4+i5+i6+i7,'test.out')
